// apps/todos-next/src/app/page.tsx
'use client';

import { useState } from 'react';

export default function Index() {
  const [todos, setTodos] = useState<{ title: string }[]>([]);

  const todoDivs = todos.map((todo) => (
    <div className="flex flex-row" key={todo.title}>
      <div>{todo.title}</div>
    </div>
  ));

  const addTodo = (title: string) => {
    setTodos([...todos, { title }]);
  };

  return (
    <div id="todosContainer" className="flex flex-col">
      {todoDivs}
      <form
        className="flex flex-row"
        onSubmit={(e) => {
          addTodo(
            (
              e.currentTarget.elements.namedItem(
                'todoInput'
              ) as HTMLInputElement
            ).value
          );
          e.preventDefault();
          (
            e.currentTarget.elements.namedItem('todoInput') as HTMLInputElement
          ).value = '';
        }}
      >
        <input id="todoInput" type="text" placeholder="Add a todo" />
        <button type="submit">Add Todo</button>
      </form>
    </div>
  );
}

// apps/todos-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  standalone: true,
  imports: [RouterModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  todos: { title: string }[] = [];

  addTodo(title: string) {
    this.todos.push({ title });
  }
}

<div id="todosContainer" class="flex flex-col">
  @for (todo of todos; track todo.title) {
  <div class="flex flex-row">
    <div>{{ todo.title }}</div>
  </div>
  }
  <form
    class="flex flex-row"
    (submit)="
      addTodo(todoInput.value); $event.preventDefault(); todoInput.value = ''
    "
  >
    <input #todoInput type="text" placeholder="Add a todo" />
    <button type="submit">Add Todo</button>
  </form>
</div>
